server:
  port: 9002

spring:
  application:
    name: bankreportingservice
  zipkin:
    base-url: http://172.22.147.179:9411
  sleuth:
    web:
      client:
        enabled: true

bank:
  management:
    url: http://bankmanagementservice

management:
  endpoints:
    web:
      exposure:
        include: refresh
