server:
  port: 9002

spring:
  application:
    name: bankreportingservice

bank:
  management:
    url: http://bankmanagementservice

management:
  endpoints:
    web:
      exposure:
        include: refresh
