server:
  port: 9001

spring:
  application:
    name: bankmanagementservice
  zipkin:
    base-url: http://172.22.147.179:9411

management:
  endpoints:
    web:
      exposure:
        include: refresh, info,health,metrics,loggers,beans,mappings,threaddump,env,caches,prometheus
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0

bank:
  security:
    url: http://localhost:7001
