server:
  port: 9002

spring:
  application:
    name: bankreportingservice


logging:
  level:
    com:
      bankreporting: trace
  file:
    name: build/bankreporting.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"