server:
  port: '7002'

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: refresh
