server:
  port: 7001

spring:
  application:
    name: bankjwtservice
  zipkin:
    base-url: http://172.22.147.179:9411
  sleuth:
    web:
      client:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: refresh, info,health,metrics,loggers,beans,mappings,threaddump,env,caches,prometheus
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://172.22.147.179:9411/api/v2/spans