server:
  port: 9001

spring:
  application:
    name: bankmanagementservice

management:
  endpoints:
    web:
      exposure:
        include: refresh

bank:
  security:
    url: http://localhost:7001