server:
  port: 7002

spring:

  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          clone-on-start: true
          uri: https://github.com/krevuru/bankconfig.git

  security:
    user:
      name: root
      password: secret
