server:
  port: 9001

spring:
  application:
    name: bankmanagementservice

management:
  endpoints:
    web:
      exposure:
        include: refresh, info,health,metrics,loggers,beans,mappings,threaddump,env,caches,prometheus
  endpoint:
    health:
      show-details: always

bank:
  security:
    url: http://localhost:7001
