server:
  port: 9001

spring:
  application:
    name: bankmanagementservice
  profiles:
    active: sit

logging:
  level:
    com:
      bankmanagement: trace
  file:
    name: build/bankmanagement.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

