server:
  port: 9002

spring:
  application:
    name: bankreportingservice
  zipkin:
    base-url: (link unavailable)
  sleuth:
    web:
      client:
        enabled: true
  cloud:
    loadbalancer:
      eureka:
        enabled: true
      ribbon:
        eureka:
          enabled: true

bank:
  management:
    url: http://bankmanagementservice

management:
  endpoints:
    web:
      exposure:
        include: refresh, info,health,metrics,loggers,beans,mappings,threaddump,env,caches,prometheus
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://172.22.147.179:9411/api/v2/spans