spring:
  jpa:
    open-in-view: false
    datasource: primary
  hibernate:
    ddl-auto: create-drop
  datasource:
    driverClassName: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@172.22.147.179:1521/freepdb1
    username: BANK_MANAGEMENT
    password: password1

  data:
    mongodb:
      host: 172.22.147.179
      port: 27017
      database: BankManagement
      username: mongoadmin
      password: Mycatch$22
      authentication-database: admin
      authentication-mechanism: SCRAM_SHA_1

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 5.0.5

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/

bankamanagement:
  dbtype:
    nosql: true

app:
  jwt:
    secret: abcdefghijklmnOPQRSTUVWXYZabcdefghijklmnOPQRSTUVWXYZabcdefghijklmnOPQRSTUVWXYZabcdefghijklmnOPQRSTUVWXYZabcdefghijklmnOPQRSTUVWXYZabcdefghijklmnOPQRSTUVWXYZabcdefghijklmnOPQRSTUVWXYZ

logging:
  level:
    com:
      bankmanagement: info
  file:
    name: build/bankmanagement-qa.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
