server:
  port: 7001

spring:
  application:
    name: bankjwtservice
  zipkin:
    base-url: http://172.22.147.179:9411
  sleuth:
    web:
      client:
        enabled: true
management:
  endpoints:
    web:
      exposure:
        include: refresh
