eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/

logging:
  level:
    com:
      bankjwtservice: info
  file:
    name: build/bankjwtservice-sit.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"


app:
  jwt:
    secret: abcdefghijklmnOPQRSTUVWXYZabcdefghijklmnOPQRSTUVWXYZabcdefghijklmnOPQRSTUVWXYZabcdefghijklmnOPQRSTUVWXYZabcdefghijklmnOPQRSTUVWXYZabcdefghijklmnOPQRSTUVWXYZabcdefghijklmnOPQRSTUVWXYZ

spring:
  jpa:
    open-in-view: false
    datasource: primary
  hibernate:
    ddl-auto: create-drop
  datasource:
    driverClassName: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@172.22.147.179:1521/freepdb1
    username: BANKSECURITY
    password: password123
